@host=http://100.89.182.96:5003
@host=http://127.0.0.1:5000

###
GET {{host}}/transactions HTTP/1.1


### 

GET {{host}}/accounts HTTP/1.1


### 

GET {{host}}/accountnames HTTP/1.1


### 

GET {{host}}/accounttransactions/expense:drink:coffee HTTP/1.1


### 

GET {{host}}/prices HTTP/1.1


### 

GET {{host}}/commodities HTTP/1.1

