[project]
name = "ipay-reflex-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pydantic>=2.11.7",
    "reflex==0.8.5",
]

[dependency-groups]
dev = [
    "ipython>=9.4.0",
]
